# Generated by Django 3.2.6 on 2021-08-20 15:06

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.TextField(default='unknown', verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
