# Generated by Django 3.2.6 on 2021-08-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210820_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.JSONField(default='{}'),
        ),
    ]
